/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: c:\projects\dos_ga~1\dampbn\res\dampbn.dat */
/* Date: Sat Nov 13 14:07:42 2021 */
/* Do not hand edit! */

#define RES_BG_LOWER                         0        /* BMP  */
#define RES_BG_RIGHT                         1        /* BMP  */
#define RES_BUTTONS                          2        /* BMP  */
#define RES_DRAWCURS                         3        /* BMP  */
#define RES_HOLYGOAT                         4        /* BMP  */
#define RES_LG_CROSS                         5        /* BMP  */
#define RES_LG_DIA                           6        /* BMP  */
#define RES_LG_PAL                           7        /* BMP  */
#define RES_LOADING                          8        /* BMP  */
#define RES_MAINAREA                         9        /* BMP  */
#define RES_NUMBERS                          10       /* BMP  */
#define RES_NUMS_HI                          11       /* BMP  */
#define RES_PAGEBUTN                         12       /* BMP  */
#define RES_PAL_COL                          13       /* BMP  */
#define RES_PALCURS                          14       /* BMP  */
#define RES_PROPFONT                         15       /* BMP  */
#define RES_SAVING                           16       /* BMP  */
#define RES_SM_PAL                           17       /* BMP  */
#define RES_TITLEBOX                         18       /* BMP  */
#define RES_WRONG                            19       /* BMP  */

