/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: c:\projects\dos_games\dampbn\res\dampbn.dat */
/* Date: Wed May 18 10:45:40 2022 */
/* Do not hand edit! */

#define RES_BG_LOWER                     0        /* BMP  */
#define RES_BG_RIGHT                     1        /* BMP  */
#define RES_BUTTONS                      2        /* BMP  */
#define RES_DRAWCURS                     3        /* BMP  */
#define RES_FINISHED                     4        /* BMP  */
#define RES_HOLYGOAT                     5        /* BMP  */
#define RES_LG_CROSS                     6        /* BMP  */
#define RES_LG_DIA                       7        /* BMP  */
#define RES_LG_PAL                       8        /* BMP  */
#define RES_LOADDIAG                     9        /* BMP  */
#define RES_LOADING                      10       /* BMP  */
#define RES_MAINAREA                     11       /* BMP  */
#define RES_MOUSE                        12       /* BMP  */
#define RES_NUMBERS                      13       /* BMP  */
#define RES_NUMS_HI                      14       /* BMP  */
#define RES_OVERCURS                     15       /* BMP  */
#define RES_PAGEBUTN                     16       /* BMP  */
#define RES_PAL_COL                      17       /* BMP  */
#define RES_PALCURS                      18       /* BMP  */
#define RES_PROPFONT                     19       /* BMP  */
#define RES_SAVING                       20       /* BMP  */
#define RES_SM_PAL                       21       /* BMP  */
#define RES_TITLEBOX                     22       /* BMP  */
#define RES_WRONG                        23       /* BMP  */
#define RES_COUNT                        24

