/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: c:\projects\dos_games\dampbn\res\dampbn.dat */
/* Date: Fri May 20 17:55:56 2022 */
/* Do not hand edit! */

#define RES_BG_LOWER                     0        /* BMP  */
#define RES_BG_RIGHT                     1        /* BMP  */
#define RES_BUTTONS                      2        /* BMP  */
#define RES_DRAWCURS                     3        /* BMP  */
#define RES_FINISHED                     4        /* BMP  */
#define RES_HELP_EXIT                    5        /* BMP  */
#define RES_HELP_NEXT                    6        /* BMP  */
#define RES_HELP_PREVIOUS                7        /* BMP  */
#define RES_HOLYGOAT                     8        /* BMP  */
#define RES_LG_CROSS                     9        /* BMP  */
#define RES_LG_DIA                       10       /* BMP  */
#define RES_LG_PAL                       11       /* BMP  */
#define RES_LOADDIAG                     12       /* BMP  */
#define RES_LOADING                      13       /* BMP  */
#define RES_MAINAREA                     14       /* BMP  */
#define RES_MOUSE                        15       /* BMP  */
#define RES_NUMBERS                      16       /* BMP  */
#define RES_NUMS_HI                      17       /* BMP  */
#define RES_OVERCURS                     18       /* BMP  */
#define RES_PAGEBUTN                     19       /* BMP  */
#define RES_PAL_COL                      20       /* BMP  */
#define RES_PALCURS                      21       /* BMP  */
#define RES_PROPFONT                     22       /* BMP  */
#define RES_SAVING                       23       /* BMP  */
#define RES_SM_PAL                       24       /* BMP  */
#define RES_TITLEBOX                     25       /* BMP  */
#define RES_WRONG                        26       /* BMP  */
#define RES_COUNT                        27

